### ISSUE TITLE
Upstreaming?

### ISSUE THREAD

**Issue by max-mapper** [kinvolk/fuse-userns-patches#4]
Hi, I'm researching the possibility of CentOS supporting fuse in user namespaces and was wondering if the goal of this repo was to upstream into the linux kernel? If so, woohoo!

**Comment by dongsupark** [comment]
Yes, exactly.
Goal is to get the patchset upstreamed into the mainline Kernel tree. The same patchset is being maintained as branches like [`dongsu/fuse-userns-v5-3-for-next` under our git repo](https://github.com/kinvolk/linux/tree/dongsu/fuse-userns-v5-3-for-next).
Currently the patchset is in the middle of review from upstream maintainers.

**Comment by dongsupark** [comment]
I think I already answered to the question. Will close this issue.
